# Generated by Django 3.1.7 on 2021-04-13 05:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('overall', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('potential', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('value', models.IntegerField()),
                ('wage', models.IntegerField()),
                ('preferred', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], max_length=5)),
                ('international_reputation', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('weak_foot', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('skill_moves', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('position', models.CharField(choices=[('LS', 'Left Striker'), ('ST', 'Striker'), ('RS', 'Right Striker'), ('LW', 'Left Winger'), ('LF', 'Left Forward'), ('CF', 'Center Forward'), ('RF', 'Right Forward'), ('RW', 'Right Winger'), ('LM', 'Left Midfielder'), ('LAM', 'Left Attacking Midfielder'), ('LDM', 'Left Defensive Midfielder'), ('LCM', 'Left Center Midfielder'), ('CAM', 'Center Attacking Midfielder'), ('CDM', 'Center Defensive Midfielder'), ('CM', 'Center Midfielder'), ('RCM', 'Right Center Midfielder'), ('RDM', 'Right Defensive Midfielder'), ('RAM', 'Right Attacking Midfielder'), ('RM', 'Right Midfielder'), ('LWB', 'Left Wingback'), ('LB', 'Left Back'), ('LCB', 'Left Center Back'), ('CB', 'Center Back'), ('RCB', 'Right Center Back'), ('RB', 'Right Back'), ('RWB', 'Right Wingback'), ('GK', 'Goalkeeper')], max_length=3)),
                ('jersey_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('joined', models.DateField(null=True)),
                ('contract_valid_until', models.DateField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='players', to='fifa.club')),
                ('loaned_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loaned_players', to='fifa.club')),
            ],
        ),
    ]
